In [277]:
%%javascript
$('#menubar').toggle();

<IPython.core.display.Javascript object>

In [2]:
import pandas as pd

In [263]:
import numpy as np

In [264]:
string_data = pd.Series(['aardvark', 'artichoke', np.nan, 'avocado'])

In [265]:
string_data

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object

In [266]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [267]:
string_data[0] = None

In [9]:
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

In [10]:
string_data.notnull()

0    False
1     True
2    False
3     True
dtype: bool

In [11]:
from numpy import nan as NA

In [269]:
data = pd.Series([1, NA, 3.5, NA, 7])

In [270]:
data.dropna() #dropna removes elements that are nans

0    1.0
2    3.5
4    7.0
dtype: float64

In [14]:
# data.dropna() <--> data[data.notnull()]

In [15]:
data = pd.DataFrame([[1., 6.5, 3.], [1., NA, NA],
                     [NA, NA, NA], [NA, 6.5, 3.]])

In [16]:
cleaned = data.dropna()

In [17]:
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [18]:
cleaned

0    1    2
0  1.0  6.5  3.0

In [20]:
data.dropna(how='all') #we can change how strict the dropping is. 
                       #here, it's only dropping rows that are entirely NA values

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [21]:
data[4] = NA  #assign a whole column to NaNs

In [22]:
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [23]:
data.dropna(axis=1, how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [24]:
df = pd.DataFrame(np.random.randn(7, 3))

In [25]:
df

0         1         2
0  0.139647 -0.283657 -0.133739
1  0.008974  0.159935  0.773679
2  0.972560 -1.679790  0.055483
3  0.469084  0.744244  0.463508
4  2.336504 -0.749218 -0.543667
5  0.598175  1.478826  0.774533
6 -0.685086 -0.010114 -0.376955

In [26]:
df.iloc[:4, 1] = NA

In [27]:
df.iloc[:2, 2] = NA

In [28]:
df

0         1         2
0  0.139647       NaN       NaN
1  0.008974       NaN       NaN
2  0.972560       NaN  0.055483
3  0.469084       NaN  0.463508
4  2.336504 -0.749218 -0.543667
5  0.598175  1.478826  0.774533
6 -0.685086 -0.010114 -0.376955

In [29]:
df.dropna()

0         1         2
4  2.336504 -0.749218 -0.543667
5  0.598175  1.478826  0.774533
6 -0.685086 -0.010114 -0.376955

In [30]:
df.dropna(thresh=2) #only drop columns if they have above the given threshold.

0         1         2
2  0.972560       NaN  0.055483
3  0.469084       NaN  0.463508
4  2.336504 -0.749218 -0.543667
5  0.598175  1.478826  0.774533
6 -0.685086 -0.010114 -0.376955

In [31]:
df.fillna(0)

0         1         2
0  0.139647  0.000000  0.000000
1  0.008974  0.000000  0.000000
2  0.972560  0.000000  0.055483
3  0.469084  0.000000  0.463508
4  2.336504 -0.749218 -0.543667
5  0.598175  1.478826  0.774533
6 -0.685086 -0.010114 -0.376955

In [33]:
df.fillna({1: 0.5, 2: 0}) #pass it a dictionary of values and we can specify a fill value

0         1         2
0  0.139647  0.500000  0.000000
1  0.008974  0.500000  0.000000
2  0.972560  0.500000  0.055483
3  0.469084  0.500000  0.463508
4  2.336504 -0.749218 -0.543667
5  0.598175  1.478826  0.774533
6 -0.685086 -0.010114 -0.376955

In [34]:
_ = df.fillna(0, inplace=True)

In [35]:
df

0         1         2
0  0.139647  0.000000  0.000000
1  0.008974  0.000000  0.000000
2  0.972560  0.000000  0.055483
3  0.469084  0.000000  0.463508
4  2.336504 -0.749218 -0.543667
5  0.598175  1.478826  0.774533
6 -0.685086 -0.010114 -0.376955

In [36]:
df = pd.DataFrame(np.random.randn(6, 3)) #we do this all the time. Making a 3x6 array of random numbers.

In [38]:
df.iloc[2:, 1] = NA

In [39]:
df.iloc[4:, 2] = NA

In [40]:
df

0         1         2
0  1.077292  2.267719 -0.710256
1  0.791908  1.203957  0.784468
2 -0.376766       NaN -1.590023
3 -0.553128       NaN -1.439003
4  1.199197       NaN       NaN
5  0.392158       NaN       NaN

In [41]:
df.fillna(method='ffill') #forward fill with the last seen value

0         1         2
0  1.077292  2.267719 -0.710256
1  0.791908  1.203957  0.784468
2 -0.376766  1.203957 -1.590023
3 -0.553128  1.203957 -1.439003
4  1.199197  1.203957 -1.439003
5  0.392158  1.203957 -1.439003

In [42]:
df.fillna(method='ffill', limit=2) #forward fill for limit number of steps

0         1         2
0  1.077292  2.267719 -0.710256
1  0.791908  1.203957  0.784468
2 -0.376766  1.203957 -1.590023
3 -0.553128  1.203957 -1.439003
4  1.199197       NaN -1.439003
5  0.392158       NaN -1.439003

In [44]:
data = pd.Series([1., NA, 3.5, NA, 7])

In [45]:
data.fillna(data.mean()) #fill our NA values with the mean

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

In [46]:
data = pd.DataFrame({'k1': ['one', 'two'] * 3 + ['two'],
                     'k2': [1, 1, 2, 3, 3, 4, 4]})

In [47]:
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [48]:
data.duplicated() #this tests whether any rows (ignoring their index) have duplicates

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [50]:
data.drop_duplicates() #there must only be one!

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [51]:
data['v1'] = range(7)

In [52]:
data.drop_duplicates(['k1'])

k1  k2  v1
0  one   1   0
1  two   1   1

In [53]:
data.drop_duplicates(['k1', 'k2'], keep='last')

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

In [54]:
data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon',
                              'Pastrami', 'corned beef', 'Bacon',
                              'pastrami', 'honey ham', 'nova lox'],
                     'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})

In [55]:
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [57]:
meat_to_animal = {
    'bacon': 'pig',
    'pulled pork': 'pig',
    'pastrami': 'cow',
    'corned beef': 'cow',
    'honey ham': 'pig',
    'nova lox': 'salmon'
}

In [58]:
lowercased = data['food'].str.lower()

In [59]:
lowercased

0          bacon
1    pulled pork
2          bacon
3       pastrami
4    corned beef
5          bacon
6       pastrami
7      honey ham
8       nova lox
Name: food, dtype: object

In [61]:
data['animal'] = lowercased.map(meat_to_animal) #pass a dict of lookups

In [62]:
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [63]:
data = pd.Series([1., -999, 2., -999., -1000., 3.])

In [64]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [65]:
data.replace(-999, np.nan) #replace just -999 with nans

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [67]:
data.replace([-999, -1000], np.nan) #replace both -999 and -1000 with nans

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [68]:
data.replace([-999, -1000], [np.nan, 0]) #replace -999 and -1000 with a different value each

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [69]:
data.replace({-999: np.nan, -1000: 0}) #replace based on a lookup table

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [70]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
                    index=['Ohio', 'Colorado', 'New York'],
                    columns=['one', 'two', 'three', 'four'])

In [71]:
transform = lambda x: x[:4].upper() #define a transformation

In [72]:
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [73]:
data.index = data.index.map(transform) #apply the transformation to the index, but not actually to the original

In [74]:
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [75]:
data.rename(index=str.title, columns=str.upper) #uppercase the column titles

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [76]:
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [79]:
data.rename(index={'OHIO': 'INDIANA'},
            columns={'three': 'peekaboo'})

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

In [80]:
data.rename(index={'OHIO': 'INDIANA'},
            columns={'three': 'peekaboo'}, inplace=True)

In [81]:
data

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

In [82]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [83]:
bins = [18, 25, 35, 60, 100]

In [84]:
cats = pd.cut(ages, bins) #split on some pre-defined bins

In [85]:
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [86]:
cats.codes #returns bin numbers

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [87]:
cats.categories #it looks like normal parens mean inclusive, and square brackets mean exclusive)

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]],
              closed='right',
              dtype='interval[int64]')

In [88]:
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [93]:
group_names = ['Youth', 'YoungAdult', 'MiddleAged', 'Senior'] #this can be whatever. it matches up with bins 1:1

In [94]:
[pd.cut(ages, bins, labels=group_names)]

[[Youth, Youth, Youth, YoungAdult, Youth, ..., YoungAdult, Senior, MiddleAged, MiddleAged, YoungAdult]
 Length: 12
 Categories (4, object): [Youth < YoungAdult < MiddleAged < Senior]]

In [97]:
data = np.random.rand(200)

In [98]:
pd.cut(data, 4, precision=2)

[(0.25, 0.5], (0.5, 0.75], (0.00085, 0.25], (0.00085, 0.25], (0.25, 0.5], ..., (0.00085, 0.25], (0.5, 0.75], (0.75, 0.99], (0.00085, 0.25], (0.75, 0.99]]
Length: 200
Categories (4, interval[float64]): [(0.00085, 0.25] < (0.25, 0.5] < (0.5, 0.75] < (0.75, 0.99]]

In [99]:
data = np.random.randn(1000)

In [100]:
cats = pd.qcut(data, 4)

In [101]:
cats

[(-0.589, 0.0621], (-3.3049999999999997, -0.589], (-3.3049999999999997, -0.589], (0.692, 2.983], (0.0621, 0.692], ..., (0.692, 2.983], (-3.3049999999999997, -0.589], (0.0621, 0.692], (-3.3049999999999997, -0.589], (0.692, 2.983]]
Length: 1000
Categories (4, interval[float64]): [(-3.3049999999999997, -0.589] < (-0.589, 0.0621] < (0.0621, 0.692] < (0.692, 2.983]]

In [102]:
pd.value_counts(cats)

(0.692, 2.983]                   250
(0.0621, 0.692]                  250
(-0.589, 0.0621]                 250
(-3.3049999999999997, -0.589]    250
dtype: int64

In [104]:
cats2 = pd.qcut(data, [0, .1, .5, .9, 1.])

In [106]:
pd.value_counts(cats2)

(0.0621, 1.235]                  400
(-1.231, 0.0621]                 400
(1.235, 2.983]                   100
(-3.3049999999999997, -1.231]    100
dtype: int64

In [107]:
data = pd.DataFrame(np.random.randn(1000, 4))

In [108]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.019031    -0.036935     0.045586    -0.016006
std       0.986014     0.994789     0.969559     0.996631
min      -3.158648    -3.016270    -3.022897    -3.580382
25%      -0.679274    -0.736944    -0.637286    -0.691793
50%       0.034188    -0.019251     0.085874    -0.032041
75%       0.684646     0.663463     0.673396     0.688051
max       3.681343     3.249868     3.475731     3.144511

In [109]:
col = data[2]

In [110]:
col[np.abs(col) > 3]

627   -3.022897
629    3.475731
Name: 2, dtype: float64

In [111]:
data[(np.abs(data) > 3).any(1)]

0         1         2         3
274 -1.335943  0.092043 -0.254266  3.144511
352 -1.361594  3.249868 -0.066440  1.173049
374 -1.266565 -0.942829 -0.576969 -3.139104
524 -0.434974 -3.016270  0.218306  1.078717
548 -0.527544  1.348179  1.668622  3.049471
563 -0.265054 -0.304395  1.201536 -3.364483
590  3.681343  0.072488 -0.584469  0.143990
627  1.709800  0.625152 -3.022897 -0.527414
629  0.375424  0.712418  3.475731 -0.275335
651 -3.158648  0.743075  0.908646  1.034863
891 -0.099305 -0.585807  0.625738 -3.580382
909 -0.001153  3.153613  0.611531 -0.644263

In [114]:
#for every item in data where the absolute value exceeds 3, replace it with -3 or 3
data[np.abs(data) > 3] = np.sign(data) * 3

In [115]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.018509    -0.037323     0.045133    -0.015116
std       0.983213     0.993463     0.967918     0.992528
min      -3.000000    -3.000000    -3.000000    -3.000000
25%      -0.679274    -0.736944    -0.637286    -0.691793
50%       0.034188    -0.019251     0.085874    -0.032041
75%       0.684646     0.663463     0.673396     0.688051
max       3.000000     3.000000     3.000000     3.000000

In [118]:
np.sign(data).head()

0    1    2    3
0  1.0  1.0  1.0  1.0
1 -1.0  1.0  1.0  1.0
2 -1.0  1.0  1.0 -1.0
3 -1.0  1.0  1.0  1.0
4 -1.0  1.0  1.0  1.0

In [120]:
df = pd.DataFrame(np.arange(5 * 4).reshape((5, 4)))

In [122]:
sampler = np.random.permutation(5)

In [123]:
sampler

array([0, 2, 4, 3, 1])

In [135]:
np.random.permutation(10) #returns a scrambled range of numbers

array([7, 0, 5, 8, 3, 6, 9, 2, 4, 1])

In [136]:
sampler

array([0, 2, 4, 3, 1])

In [138]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [139]:
df.take(sampler)

0   1   2   3
0   0   1   2   3
2   8   9  10  11
4  16  17  18  19
3  12  13  14  15
1   4   5   6   7

In [142]:
df.sample(n=3) #just pull a few rows out, don't alter the state of df

0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [143]:
choices = pd.Series([5, 7, -1, 6, 4])

In [144]:
draws = choices.sample(n=10, replace=True)

In [158]:
draws #returns the index of the pulls from choices.

2   -1
1    7
3    6
2   -1
3    6
4    4
1    7
3    6
3    6
1    7
dtype: int64

In [159]:
choices.sample(n=1)

3    6
dtype: int64

In [160]:
df = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'],
                   'data1': range(6)})

In [161]:
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [164]:
pd.get_dummies(df['key']) #returns a matrix of ones or zeroes based on which key each item is?

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [165]:
dummies = pd.get_dummies(df['key'], prefix='key')

In [166]:
df_with_dummy = df[['data1']].join(dummies) #glue together two datasets

In [168]:
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [169]:
df_with_dummy

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

### 

In [170]:
mnames = ['movie_id', 'title', 'genres']

In [173]:
movies = pd.read_csv('../pydata-book/datasets/movielens/movies.dat', sep='::',
                       header=None, names=mnames)

/home/aaron/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  


In [174]:
movies[:10] #the first ten lines

movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [175]:
all_genres = []

In [176]:
movies.genres.head(10)

0     Animation|Children's|Comedy
1    Adventure|Children's|Fantasy
2                  Comedy|Romance
3                    Comedy|Drama
4                          Comedy
5           Action|Crime|Thriller
6                  Comedy|Romance
7            Adventure|Children's
8                          Action
9       Action|Adventure|Thriller
Name: genres, dtype: object

In [179]:
for x in movies.genres: #if we see an "unexpected EOF while parsing" that means
                        #we haven't finished typing in the full code block.
        all_genres.extend(x.split('|'))
    

In [181]:
genres = pd.unique(all_genres) 

In [182]:
genres

array(['Animation', "Children's", 'Comedy', 'Adventure', 'Fantasy',
       'Romance', 'Drama', 'Action', 'Crime', 'Thriller', 'Horror',
       'Sci-Fi', 'Documentary', 'War', 'Musical', 'Mystery', 'Film-Noir',
       'Western'], dtype=object)

In [184]:
zero_matrix = np.zeros((len(movies), len(genres))) #create an array of zeros x wide by y tall

In [188]:
zero_matrix[:10]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.]])

In [189]:
dummies = pd.DataFrame(zero_matrix, columns=genres)

In [192]:
movies.genres[0]

"Animation|Children's|Comedy"

In [191]:
gen = movies.genres[0]

In [193]:
gen.split('|')

['Animation', "Children's", 'Comedy']

In [194]:
dummies.columns.get_indexer(gen.split('|'))

array([0, 1, 2])

In [197]:
for i, gen in enumerate(movies.genres):
    indices = dummies.columns.get_indexer(gen.split('|'))
    dummies.iloc[i, indices] = 1

In [200]:
movies_windic = movies.join(dummies.add_prefix('Genre_'))

In [275]:
movies_windic.iloc[0]

movie_id                                       1
title                           Toy Story (1995)
genres               Animation|Children's|Comedy
Genre_Animation                                1
Genre_Children's                               1
Genre_Comedy                                   1
Genre_Adventure                                0
Genre_Fantasy                                  0
Genre_Romance                                  0
Genre_Drama                                    0
Genre_Action                                   0
Genre_Crime                                    0
Genre_Thriller                                 0
Genre_Horror                                   0
Genre_Sci-Fi                                   0
Genre_Documentary                              0
Genre_War                                      0
Genre_Musical                                  0
Genre_Mystery                                  0
Genre_Film-Noir                                0
Genre_Western       

In [202]:
np.random.seed(12345)

In [203]:
values = np.random.rand(10)

In [204]:
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [208]:
bins = [0, .2, .4, .6, .8, 1]

In [210]:
pd.cut(values, bins)

[(0.8, 1.0], (0.2, 0.4], (0.0, 0.2], (0.2, 0.4], (0.4, 0.6], (0.4, 0.6], (0.8, 1.0], (0.6, 0.8], (0.6, 0.8], (0.6, 0.8]]
Categories (5, interval[float64]): [(0.0, 0.2] < (0.2, 0.4] < (0.4, 0.6] < (0.6, 0.8] < (0.8, 1.0]]

In [211]:
pd.get_dummies(pd.cut(values, bins)) #I don't quite understand the significance of this?

   (0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           0           1
1           0           1           0           0           0
2           1           0           0           0           0
3           0           1           0           0           0
4           0           0           1           0           0
5           0           0           1           0           0
6           0           0           0           0           1
7           0           0           0           1           0
8           0           0           0           1           0
9           0           0           0           1           0

In [212]:
val = 'a, b,   guido'

In [213]:
val.split(',')

['a', ' b', '   guido']

In [214]:
pieces = [x.strip() for x in val.split(',')] # by default takes out all whitespace, even tabs

In [215]:
pieces

['a', 'b', 'guido']

In [216]:
first, second, third = pieces

In [217]:
first + '::' + second + '::' + third

'a::b::guido'

In [219]:
'::'.join(pieces)

'a::b::guido'

In [220]:
'guido' in val

True

In [222]:
val.index(',')

1

In [227]:
val.index(':')

ValueError: substring not found

In [226]:
val.find(':') #ooh! find just throws a negative number instead of complaining with an exception if the string isnt there.

-1

In [228]:
val.count(',')

2

In [230]:
val.replace(',', '::')

'a:: b::   guido'

In [231]:
val = "LRLRLRRMM"

In [232]:
val.replace('LRL', 'MMM') #I'm doing something really hacky and awful in my async game.

'MMMRLRRMM'

In [233]:
val.replace(',', '')

'LRLRLRRMM'

In [234]:
import re

In [235]:
text = 'foo     bar\t baz   \tqux'

In [236]:
re.split('\s+', text)

['foo', 'bar', 'baz', 'qux']

In [237]:
regex = re.compile('\s+')

In [238]:
regex.split(text)

['foo', 'bar', 'baz', 'qux']

In [239]:
regex.findall(text) #find just the stuff that matches the regex

['     ', '\t ', '   \t']

In [240]:
#use regexes when you're going to be repeating something a LOT of times.

In [241]:
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com
"""

In [242]:
pattern = r'[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}'

In [244]:
regex = re.compile(pattern, flags=re.IGNORECASE)

In [245]:
regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

In [276]:
print(regex.sub('REDACTED', text)) #substitute out everything that matches

Dave REDACTED
Steve REDACTED
Rob REDACTED
Ryan REDACTED



In [247]:
#regexes can be segmented by partitioning the matches with normal parens

In [248]:
data = {'Dave': 'dave@google.com', 'Steve': 'steve@gmail.com',
        'Rob': 'rob@gmail.com', 'Wes': np.nan}

In [249]:
data = pd.Series(data)

In [250]:
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [251]:
data.isnull()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [252]:
data.str.contains('gmail')

Dave     False
Steve     True
Rob       True
Wes        NaN
dtype: object

In [253]:
pattern

'[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,4}'

In [256]:
pattern = '([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\\.([A-Z]{2,4})'

In [257]:
data.str.findall(pattern, flags=re.IGNORECASE)

Dave     [(dave, google, com)]
Steve    [(steve, gmail, com)]
Rob        [(rob, gmail, com)]
Wes                        NaN
dtype: object

In [258]:
matches = data.str.match(pattern, flags=re.IGNORECASE)

In [259]:
matches

Dave     True
Steve    True
Rob      True
Wes       NaN
dtype: object

In [260]:
matches.str.get(1)

Dave    NaN
Steve   NaN
Rob     NaN
Wes     NaN
dtype: float64

In [261]:
matches.str[0]

Dave    NaN
Steve   NaN
Rob     NaN
Wes     NaN
dtype: float64

In [262]:
data.str[:5]

Dave     dave@
Steve    steve
Rob      rob@g
Wes        NaN
dtype: object