In [134]:
%%javascript
$('#menubar').toggle();

<IPython.core.display.Javascript object>

In [7]:
import pandas as pd
import numpy as np

In [8]:
data = pd.Series(np.random.randn(9),
                 index=[['a', 'a', 'a', 'b', 'b', 'c', 'c', 'd', 'd'],
                        [1, 2, 3, 1, 3, 1, 2, 2, 3]])

In [9]:
data

a  1    0.425038
   2    0.730346
   3   -0.850462
b  1    0.308961
   3    0.429897
c  1    0.499978
   2    0.244720
d  2    1.078453
   3   -0.234546
dtype: float64

In [10]:
data.index

MultiIndex(levels=[['a', 'b', 'c', 'd'], [1, 2, 3]],
           codes=[[0, 0, 0, 1, 1, 2, 2, 3, 3], [0, 1, 2, 0, 2, 0, 1, 1, 2]])

In [11]:
data['b']

1    0.308961
3    0.429897
dtype: float64

In [12]:
data['b':'c']

b  1    0.308961
   3    0.429897
c  1    0.499978
   2    0.244720
dtype: float64

In [13]:
data.loc[['b', 'd']]

b  1    0.308961
   3    0.429897
d  2    1.078453
   3   -0.234546
dtype: float64

In [14]:
data.loc[:, 2]

a    0.730346
c    0.244720
d    1.078453
dtype: float64

In [15]:
data.unstack()

1         2         3
a  0.425038  0.730346 -0.850462
b  0.308961       NaN  0.429897
c  0.499978  0.244720       NaN
d       NaN  1.078453 -0.234546

In [16]:
data.unstack().stack()

a  1    0.425038
   2    0.730346
   3   -0.850462
b  1    0.308961
   3    0.429897
c  1    0.499978
   2    0.244720
d  2    1.078453
   3   -0.234546
dtype: float64

In [17]:
frame = pd.DataFrame(np.arange(12).reshape((4, 3)),
                     index=[['a', 'a', 'b', 'b'], [1, 2, 1, 2]],
                     columns=[['Ohio', 'Ohio', 'Colorado',],
                              ['Green', 'Red', 'Green']])

In [18]:
frame

Ohio     Colorado
    Green Red    Green
a 1     0   1        2
  2     3   4        5
b 1     6   7        8
  2     9  10       11

In [19]:
frame.index.names = ['key1', 'key2']

In [20]:
frame.columns.names = ['state', 'color']

In [21]:
frame

state      Ohio     Colorado
color     Green Red    Green
key1 key2                   
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [22]:
frame['Ohio']

color      Green  Red
key1 key2            
a    1         0    1
     2         3    4
b    1         6    7
     2         9   10

In [23]:
frame.swaplevel('key1', 'key2')

state      Ohio     Colorado
color     Green Red    Green
key2 key1                   
1    a        0   1        2
2    a        3   4        5
1    b        6   7        8
2    b        9  10       11

In [24]:
frame

state      Ohio     Colorado
color     Green Red    Green
key1 key2                   
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [25]:
frame.swaplevel(0, 1).sort_index(level=0)

state      Ohio     Colorado
color     Green Red    Green
key2 key1                   
1    a        0   1        2
     b        6   7        8
2    a        3   4        5
     b        9  10       11

In [26]:
frame

state      Ohio     Colorado
color     Green Red    Green
key1 key2                   
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [28]:
df1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],
                    'data1': range(7)})

In [31]:
df2 = pd.DataFrame({'key': ['a', 'b', 'd'],
                    'data2': range(3)})

In [32]:
df1

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6

In [33]:
df2

key  data2
0   a      0
1   b      1
2   d      2

In [34]:
pd.merge(df1, df2)

key  data1  data2
0   b      0      1
1   b      1      1
2   b      6      1
3   a      2      0
4   a      4      0
5   a      5      0

In [35]:
#I'm not understanding the section on merging.

In [36]:
lefth = pd.DataFrame({'key1': ['Ohio', 'Ohio', 'Ohio',
                               'Nevada', 'Nevada'],
                      'key2': [2000, 2001, 2002, 2001, 2002],
                      'data': np.arange(5.)})

In [37]:
righth = pd.DataFrame(np.arange(12).reshape((6, 2)),
                      index=[['Nevada', 'Nevada', 'Ohio', 'Ohio',
                              'Ohio', 'Ohio'],
                             [2001, 2002, 2000, 2000, 2001, 2002]],
                      columns=['event1', 'event2'])

In [38]:
lefth

key1  key2  data
0    Ohio  2000   0.0
1    Ohio  2001   1.0
2    Ohio  2002   2.0
3  Nevada  2001   3.0
4  Nevada  2002   4.0

In [40]:
righth

event1  event2
Nevada 2001       0       1
       2002       2       3
Ohio   2000       4       5
       2000       6       7
       2001       8       9
       2002      10      11

Here, we're accepting the index of the right half of the merge (state and year), and binding the correct keys from the left half to the matched pair of indexes from the right (key1 and key2 for state and year accordingly)

In [41]:
pd.merge(lefth, righth, left_on=['key1', 'key2'], right_index=True)

key1  key2  data  event1  event2
0    Ohio  2000   0.0       4       5
0    Ohio  2000   0.0       6       7
1    Ohio  2001   1.0       8       9
2    Ohio  2002   2.0      10      11
3  Nevada  2001   3.0       0       1
4  Nevada  2002   4.0       2       3

In [42]:
arr = np.arange(12).reshape((3, 4))

In [43]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [44]:
np.concatenate([arr, arr], axis=1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [45]:
s1 = pd.Series([0, 1], index=['a', 'b'])

In [46]:
s2 = pd.Series([2, 3, 4], index=['c', 'd', 'e'])

In [47]:
s3 = pd.Series([5, 6], index=['f', 'g'])

In [48]:
pd.concat([s1, s2, s3])

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

In [50]:
pd.concat([s1, s2, s3], axis=1, sort=True)

0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0

In [51]:
s4 = pd.concat([s1, s3])

In [52]:
s4

a    0
b    1
f    5
g    6
dtype: int64

In [54]:
pd.concat([s1, s4], axis=1, sort=True)

0  1
a  0.0  0
b  1.0  1
f  NaN  5
g  NaN  6

In [56]:
 pd.concat([s1, s4], axis=1, join='inner')

0  1
a  0  0
b  1  1

In [57]:
result = pd.concat([s1, s1, s3], keys=['one', 'two', 'three'])

In [58]:
result

one    a    0
       b    1
two    a    0
       b    1
three  f    5
       g    6
dtype: int64

In [60]:
result.unstack()

a    b    f    g
one    0.0  1.0  NaN  NaN
two    0.0  1.0  NaN  NaN
three  NaN  NaN  5.0  6.0

In [61]:
df1 = pd.DataFrame(np.arange(6).reshape(3, 2), index=['a', 'b', 'c'],
                   columns=['one', 'two'])

In [63]:
df2 = pd.DataFrame(5 + np.arange(4).reshape(2, 2), index=['a', 'c'],
                   columns=['three', 'four'])

In [64]:
df1

one  two
a    0    1
b    2    3
c    4    5

In [65]:
df2

three  four
a      5     6
c      7     8

In [67]:
pd.concat([df1, df2], axis=1, keys=['level1', 'level2'], sort=True)

level1     level2     
     one two  three four
a      0   1    5.0  6.0
b      2   3    NaN  NaN
c      4   5    7.0  8.0

In [72]:
df1 = pd.DataFrame(np.random.randn(3, 4), columns=['a', 'b', 'c', 'd']) #for shape, it's y then x

In [73]:
df2 = pd.DataFrame(np.random.randn(2, 3), columns=['b', 'd', 'a'])

In [77]:
pd.concat([df1, df2], ignore_index=True, sort=True)

a         b         c         d
0  2.109110  0.293742  0.333430 -1.595356
1  0.519441  0.865656  0.052814 -1.000342
2 -1.630316 -0.358720  1.975432 -0.992342
3 -0.344379 -0.606186       NaN -0.046518
4 -1.403914 -0.693935       NaN -0.287688

### OVERLAP:

In [78]:
a = pd.Series([np.nan, 2.5, np.nan, 3.5, 4.5, np.nan],
              index=['f', 'e', 'd', 'c', 'b', 'a'])

In [80]:
b = pd.Series(np.arange(len(a), dtype=np.float64),
                        index=['f', 'e', 'd', 'c', 'b', 'a'])

In [82]:
b[-1] = np.nan

In [83]:
a

f    NaN
e    2.5
d    NaN
c    3.5
b    4.5
a    NaN
dtype: float64

In [84]:
b

f    0.0
e    1.0
d    2.0
c    3.0
b    4.0
a    NaN
dtype: float64

In [85]:
np.where(pd.isnull(a), b, a)

array([0. , 2.5, 2. , 3.5, 4.5, nan])

In [87]:
b[:-2].combine_first(a[2:])

a    NaN
b    4.5
c    3.0
d    2.0
e    1.0
f    0.0
dtype: float64

In [89]:
df1 = pd.DataFrame({'a': [1., np.nan, 5., np.nan],
                    'b': [np.nan, 2., np.nan, 6.],
                    'c':range(2, 18, 4)})

In [91]:
df2 = pd.DataFrame({'a': [5., 4., np.nan, 3., 7.],
                    'b': [np.nan, 3., 4., 6., 8.]})

In [92]:
df1

a    b   c
0  1.0  NaN   2
1  NaN  2.0   6
2  5.0  NaN  10
3  NaN  6.0  14

In [93]:
df2

a    b
0  5.0  NaN
1  4.0  3.0
2  NaN  4.0
3  3.0  6.0
4  7.0  8.0

In [94]:
df1.combine_first(df2)

a    b     c
0  1.0  NaN   2.0
1  4.0  2.0   6.0
2  5.0  4.0  10.0
3  3.0  6.0  14.0
4  7.0  8.0   NaN

### RESHAPING AND PIVOTING

In [97]:
data = pd.DataFrame(np.arange(6).reshape((2, 3)),
                    index=pd.Index(['Ohio', 'Colorado'], name='state'),
                    columns=pd.Index(['one', 'two', 'three'],
                    name='number'))

In [98]:
data

number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5

In [102]:
result = data.stack() #layering each level L to R, one after the other sequentially?

In [103]:
result 

state     number
Ohio      one       0
          two       1
          three     2
Colorado  one       3
          two       4
          three     5
dtype: int64

In [105]:
result

state     number
Ohio      one       0
          two       1
          three     2
Colorado  one       3
          two       4
          three     5
dtype: int64

In [106]:
result

state     number
Ohio      one       0
          two       1
          three     2
Colorado  one       3
          two       4
          three     5
dtype: int64

In [107]:
result.unstack(0)

state   Ohio  Colorado
number                
one        0         3
two        1         4
three      2         5

In [108]:
result.unstack('state')

state   Ohio  Colorado
number                
one        0         3
two        1         4
three      2         5

In [109]:
s1 = pd.Series([0, 1, 2, 3], index=['a', 'b', 'c', 'd'])

In [110]:
s2 = pd.Series([4, 5, 6], index=['c', 'd', 'e'])

In [111]:
data2 = pd.concat([s1, s2], keys=['one', 'two'])

In [112]:
data2

one  a    0
     b    1
     c    2
     d    3
two  c    4
     d    5
     e    6
dtype: int64

In [113]:
data2.unstack()

a    b    c    d    e
one  0.0  1.0  2.0  3.0  NaN
two  NaN  NaN  4.0  5.0  6.0

In [114]:
data2.unstack()

a    b    c    d    e
one  0.0  1.0  2.0  3.0  NaN
two  NaN  NaN  4.0  5.0  6.0

In [115]:
data = pd.read_csv('../pydata-book/examples/macrodata.csv')

In [116]:
data.head()

year  quarter   realgdp  realcons  realinv  realgovt  realdpi    cpi  \
0  1959.0      1.0  2710.349    1707.4  286.898   470.045   1886.9  28.98   
1  1959.0      2.0  2778.801    1733.7  310.859   481.301   1919.7  29.15   
2  1959.0      3.0  2775.488    1751.8  289.226   491.260   1916.4  29.35   
3  1959.0      4.0  2785.204    1753.7  299.356   484.052   1931.3  29.37   
4  1960.0      1.0  2847.699    1770.5  331.722   462.199   1955.5  29.54   

      m1  tbilrate  unemp      pop  infl  realint  
0  139.7      2.82    5.8  177.146  0.00     0.00  
1  141.7      3.08    5.1  177.830  2.34     0.74  
2  140.5      3.82    5.3  178.657  2.74     1.09  
3  140.0      4.33    5.6  179.386  0.27     4.06  
4  139.6      3.50    5.2  180.007  2.31     1.19

In [117]:
periods = pd.PeriodIndex(year=data.year, quarter=data.quarter,
                         name='date')

In [118]:
columns = pd.Index(['realgdp', 'infl', 'unemp'], name='item')

In [119]:
data = data.reindex(columns=columns)

In [120]:
data.head()

item   realgdp  infl  unemp
0     2710.349  0.00    5.8
1     2778.801  2.34    5.1
2     2775.488  2.74    5.3
3     2785.204  0.27    5.6
4     2847.699  2.31    5.2

In [121]:
data.index = periods.to_timestamp('D', 'end')

In [122]:
ldata = data.stack().reset_index().rename(columns={0: 'value'})

In [123]:
ldata[:10]

date     item     value
0 1959-03-31 23:59:59.999999999  realgdp  2710.349
1 1959-03-31 23:59:59.999999999     infl     0.000
2 1959-03-31 23:59:59.999999999    unemp     5.800
3 1959-06-30 23:59:59.999999999  realgdp  2778.801
4 1959-06-30 23:59:59.999999999     infl     2.340
5 1959-06-30 23:59:59.999999999    unemp     5.100
6 1959-09-30 23:59:59.999999999  realgdp  2775.488
7 1959-09-30 23:59:59.999999999     infl     2.740
8 1959-09-30 23:59:59.999999999    unemp     5.300
9 1959-12-31 23:59:59.999999999  realgdp  2785.204

In [126]:
pivoted = ldata.pivot('date', 'item', 'value')

In [128]:
pivoted[:10]

item                           infl   realgdp  unemp
date                                                
1959-03-31 23:59:59.999999999  0.00  2710.349    5.8
1959-06-30 23:59:59.999999999  2.34  2778.801    5.1
1959-09-30 23:59:59.999999999  2.74  2775.488    5.3
1959-12-31 23:59:59.999999999  0.27  2785.204    5.6
1960-03-31 23:59:59.999999999  2.31  2847.699    5.2
1960-06-30 23:59:59.999999999  0.14  2834.390    5.2
1960-09-30 23:59:59.999999999  2.70  2839.022    5.6
1960-12-31 23:59:59.999999999  1.21  2802.616    6.3
1961-03-31 23:59:59.999999999 -0.40  2819.264    6.8
1961-06-30 23:59:59.999999999  1.47  2872.005    7.0

In [132]:
ldata['value2'] =  np.random.randn(len(ldata))

In [133]:
ldata[:10]

date     item     value    value2
0 1959-03-31 23:59:59.999999999  realgdp  2710.349  0.684483
1 1959-03-31 23:59:59.999999999     infl     0.000 -1.176359
2 1959-03-31 23:59:59.999999999    unemp     5.800 -1.038844
3 1959-06-30 23:59:59.999999999  realgdp  2778.801  1.526403
4 1959-06-30 23:59:59.999999999     infl     2.340  0.354754
5 1959-06-30 23:59:59.999999999    unemp     5.100 -0.581982
6 1959-09-30 23:59:59.999999999  realgdp  2775.488 -2.316166
7 1959-09-30 23:59:59.999999999     infl     2.740 -1.455225
8 1959-09-30 23:59:59.999999999    unemp     5.300  0.184920
9 1959-12-31 23:59:59.999999999  realgdp  2785.204 -0.990534